export const siteUrl = process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, '') || (process.env.VERCEL_PROJECT_PRODUCTION_URL ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}` : 'http://localhost:3000');
export const whatsapp = (message = 'مرحبًا VALYNEX، أود طلب عرض سعر لحلول المعامل والتجهيزات الطبية.') => `https://wa.me/201037779413?text=${encodeURIComponent(message)}`;
export const categories = [
 {id:'equipment',name:'أجهزة وتجهيزات المعامل',en:'LABORATORY EQUIPMENT',text:'أرسل نوع الجهاز، والمواصفات أو الموديل المطلوب، وطبيعة استخدامه في المعمل.',items:['أجهزة المعامل','تجهيزات العمل اليومية','حلول تطوير المعمل'],icon:'01',image:'/images/lab-equipment-real.webp',alt:'أخصائي يشغّل جهاز طرد مركزي داخل معمل؛ صورة مرجعية'},
 {id:'supplies',name:'مستلزمات المعامل',en:'LABORATORY SUPPLIES',text:'مستهلكات ومستلزمات التشغيل. اذكر الأصناف والكميات وأي جهاز يلزم التوافق معه.',items:['مستهلكات المعامل','مستلزمات التشغيل','طلبات التوريد الدورية'],icon:'02',image:'/images/rapid-test-real.webp',alt:'أدوات اختبارات سريعة؛ صورة مرجعية لمستلزمات الفحص'},
 {id:'medical',name:'تجهيزات طبية',en:'MEDICAL SOLUTIONS',text:'طلبات تجهيز للمنشآت الطبية، تُراجع بحسب التخصص وقائمة المتطلبات.',items:['تجهيزات المنشآت','مستلزمات طبية','حلول بحسب التخصص'],icon:'03',image:'/images/lab-equipment-real.webp',alt:'جهاز طرد مركزي أثناء الاستخدام؛ صورة مرجعية للنشاط'},
 {id:'services',name:'حلول التوريد والتجهيز',en:'PROCUREMENT & SETUP',text:'اجمع احتياجاتك في قائمة واحدة، مع المواصفات والكميات ومكان التوريد.',items:['مراجعة الاحتياجات','تجميع طلبات التوريد','تنسيق نطاق التجهيز'],icon:'04',image:'/images/lab-people-real.webp',alt:'أخصائي يعمل بميكروسكوب؛ صورة مرجعية لبيئة المعمل'},
 {id:'rapid',name:'أجهزة التحاليل السريعة',en:'RAPID & POINT-OF-CARE',text:'حدد نوع الاختبار والقارئ المطلوب ومستلزمات تشغيله، لنراجع نطاق الطلب.',items:['قارئات الاختبارات السريعة','أنظمة الفحص بالقرب من المريض','مستلزمات الاختبارات المتوافقة'],icon:'05',image:'/images/rapid-test-real.webp',alt:'اختبارات سريعة؛ صورة مرجعية للفئة وليست صورة قارئ معروض للبيع'}
];
